version : '3.7'
 * @date : 2023/7/15 10:46 
 */

 services: 
  backend-ts-app:
    container-name: backend-ts-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./

#  docker-compose up -d